### ISSUE TITLE
Diretório 'services' não existe dentro de 'libs'

### ISSUE THREAD

**Issue by JNussenzveig** [DevelopersRede/erede-node#1]
O diretório "services" que esta sendo required em erede.js não consta no repositório...

**Comment by netojoaobatista** [comment]
Verificando o que ocorreu na hora do push.

**Comment by JNussenzveig** [comment]
> Verificando o que ocorreu na hora do push.

Alguma novidade? Desculpe incomodar, mas estamos precisando da library urgente para lançar uma plataforma...

**Comment by JNussenzveig** [comment]
@netojoaobatista poderia liberar o "services" e enviar o commit?

**Comment by netojoaobatista** [comment]
@JNussens, o que aconteceu foi que esse código foi escrito numa máquina backup; eu já estou recuperando a imagem do hdd dela para conseguir liberar esse diretório.

**Comment by antoniogeroncio** [comment]
Olá @netojoaobatista, é uma satisfação falar com você! Tem alguma novidade sobre os arquivos? Desde já obrigado.
